# hoanganht1k27
---
- name: IPTABLES [Step 01] - Stop Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: IPTABLES [Step 02] - Install Iptables
  yum:
    name: ['iptables', 'iptables-services']
    state: latest

- name: IPTABLES [Step 03]-[Single] - Add haproxy pve exporter port to config file
  lineinfile:
    dest: /etc/sysconfig/iptables
    insertbefore: '-A INPUT -j REJECT --reject-with icmp-host-prohibited'
    line: '{{ item }}'
    state: present
  with_items:
    - "# HAPROXY PVE EXPORTER #"
    - "-A INPUT -p tcp -m state --state NEW -m tcp --dport {{ haproxy_pve_exporter_port }} -m comment --comment \"Haproxy pve exporter port\" -j ACCEPT"
  when: '"pve_exporter" in haproxy_type'

- name: IPTABLES [Step 04] - Add haproxy pve exporter port to Firewall
  iptables:
    action: "insert"
    chain: INPUT
    protocol: tcp
    destination_port: "{{ haproxy_pve_exporter_port | int}}"
    ctstate: NEW
    comment: "Haproxy pve exporter port"
    jump: ACCEPT
  when: '"pve_exporter" in haproxy_type'


- name: IPTABLES [Step 05]-[Single] - Add haproxy vmware exporter port to config file
  lineinfile:
    dest: /etc/sysconfig/iptables
    insertbefore: '-A INPUT -j REJECT --reject-with icmp-host-prohibited'
    line: '{{ item }}'
    state: present
  with_items:
    - "# HAPROXY VMWARE EXPORTER #"
    - "-A INPUT -p tcp -m state --state NEW -m tcp --dport {{ haproxy_vmware_exporter_port }} -m comment --comment \"Haproxy vmware exporter port\" -j ACCEPT"
  when: '"vmware_expoter" in haproxy_type'

- name: IPTABLES [Step 06] - Add haproxy vmware exporter port to Firewall
  iptables:
    action: "insert"
    chain: INPUT
    protocol: tcp
    destination_port: "{{ haproxy_vmware_exporter_port | int}}"
    ctstate: NEW
    comment: "Haproxy vmware exporter port"
    jump: ACCEPT
  when: '"vmware_exporter" in haproxy_type'
