- hosts: prometheus
  remote_user: root
  tasks:
    - include_role:
        name: docker
    - name: Install iptables package
      yum:
        name: iptables
        state: present
    - include_role:
        name: prometheus
