- name: RUN VMWARE EXPORTER [Step 01] - Run
  command: "docker run --name {{ container_name }} --rm -d -p {{ vmware_exporter_port }}:9272 -v {{ vmware_exporter_config_path }}:/opt/vmware_exporter/esx.yml pryorda/vmware_exporter --config /opt/vmware_exporter/esx.yml"
  when: vmware_conf.changed or vmware_container.failed
