- name: Run vmware exporter
  command: "docker run --name {{ container_name }} --rm -d -p {{ vmware_exporter_port }}:9272 -v {{ default_config_path }}:/opt/vmware_exporter/esx.yml pryorda/vmware_exporter --config /opt/vmware_exporter/esx.yml"

