- name: Copy config file
  copy:
    src: esx.yml
    dest: "{{ default_config_path }}"
  register: vmware_conf
- name: Check docker container is running or not
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ vmware_exporter_port }}"
    state: started
    delay: 0
    timeout: 3
  ignore_errors: yes
  register: vmware_container
#- name: Debug
#  debug:
#    var: vmware_container
- name: Stop old docker container
  command: docker stop {{ container_name }}
  ignore_errors: true
  when: vmware_conf.changed or vmware_container.failed
- name: Remove old docker container
  command: docker remove {{ container_name }}
  ignore_errors: true
  when: vmware_conf.changed or vmware_container.failed
- name: Open port {{ vmware_exporter_port }} with iptables
  iptables:
    action: "insert"
    chain: INPUT
    protocol: tcp
    destination_port: "{{ vmware_exporter_port | int }}"
    jump: ACCEPT
